In [35]:
# Dependencies
import pandas as pd

In [36]:
# Name of the CSV file
data = '../Resources/database.csv'

In [37]:
# The correct encoding must be used to read the CSV in pandas
df = pd.read_csv(data, encoding="ISO-8859-1")
df

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,198532,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,February,1,Murder or Manslaughter,...,Unknown,Male,49,White,Unknown,Girlfriend,Handgun,0,0,FBI
1,198533,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,April,1,Murder or Manslaughter,...,Unknown,Male,18,White,Unknown,Stranger,Handgun,0,1,FBI
2,198534,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,April,2,Murder or Manslaughter,...,Unknown,Male,28,Native American/Alaska Native,Unknown,Girlfriend,Blunt Object,0,0,FBI
3,198535,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,June,1,Murder or Manslaughter,...,Unknown,Male,21,Native American/Alaska Native,Unknown,Stranger,Blunt Object,0,0,FBI
4,198536,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,August,1,Murder or Manslaughter,...,Unknown,Male,21,White,Unknown,Acquaintance,Handgun,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439918,638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
439919,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
439920,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
439921,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
439922,638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

In [39]:
# If wanting to delete columns
del df['Victim Count']
df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Race,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Perpetrator Count,Record Source
0,198532,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,February,1,Murder or Manslaughter,...,White,Unknown,Male,49,White,Unknown,Girlfriend,Handgun,0,FBI
1,198533,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,April,1,Murder or Manslaughter,...,White,Unknown,Male,18,White,Unknown,Stranger,Handgun,1,FBI
2,198534,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,April,2,Murder or Manslaughter,...,Native American/Alaska Native,Unknown,Male,28,Native American/Alaska Native,Unknown,Girlfriend,Blunt Object,0,FBI
3,198535,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,June,1,Murder or Manslaughter,...,White,Unknown,Male,21,Native American/Alaska Native,Unknown,Stranger,Blunt Object,0,FBI
4,198536,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,August,1,Murder or Manslaughter,...,White,Unknown,Male,21,White,Unknown,Acquaintance,Handgun,0,FBI

In [40]:
# If wanting to delete columns
del df['Perpetrator Count']
df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Age,Victim Race,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Record Source
0,198532,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,February,1,Murder or Manslaughter,...,45,White,Unknown,Male,49,White,Unknown,Girlfriend,Handgun,FBI
1,198533,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,April,1,Murder or Manslaughter,...,23,White,Unknown,Male,18,White,Unknown,Stranger,Handgun,FBI
2,198534,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,April,2,Murder or Manslaughter,...,29,Native American/Alaska Native,Unknown,Male,28,Native American/Alaska Native,Unknown,Girlfriend,Blunt Object,FBI
3,198535,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,June,1,Murder or Manslaughter,...,69,White,Unknown,Male,21,Native American/Alaska Native,Unknown,Stranger,Blunt Object,FBI
4,198536,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1990,August,1,Murder or Manslaughter,...,21,White,Unknown,Male,21,White,Unknown,Acquaintance,Handgun,FBI

In [41]:
# Identify # of rows
df.count()

Record ID                439923
Agency Code              439923
Agency Name              439923
Agency Type              439923
City                     439923
State                    439923
Year                     439923
Month                    439923
Incident                 439923
Crime Type               439923
Crime Solved             439923
Victim Sex               439923
Victim Age               439923
Victim Race              439923
Victim Ethnicity         439923
Perpetrator Sex          439923
Perpetrator Age          439923
Perpetrator Race         439923
Perpetrator Ethnicity    439923
Relationship             439923
Weapon                   439923
Record Source            439923
dtype: int64

In [42]:
# Drop all rows with missing information *turns out there aren't any*
df = df.dropna(how='any')

In [43]:
 # Verify dropped rows
df.count()

Record ID                439923
Agency Code              439923
Agency Name              439923
Agency Type              439923
City                     439923
State                    439923
Year                     439923
Month                    439923
Incident                 439923
Crime Type               439923
Crime Solved             439923
Victim Sex               439923
Victim Age               439923
Victim Race              439923
Victim Ethnicity         439923
Perpetrator Sex          439923
Perpetrator Age          439923
Perpetrator Race         439923
Perpetrator Ethnicity    439923
Relationship             439923
Weapon                   439923
Record Source            439923
dtype: int64

In [44]:
# What type of data is each column?
df.dtypes

Record ID                 int64
Agency Code              object
Agency Name              object
Agency Type              object
City                     object
State                    object
Year                      int64
Month                    object
Incident                  int64
Crime Type               object
Crime Solved             object
Victim Sex               object
Victim Age                int64
Victim Race              object
Victim Ethnicity         object
Perpetrator Sex          object
Perpetrator Age           int64
Perpetrator Race         object
Perpetrator Ethnicity    object
Relationship             object
Weapon                   object
Record Source            object
dtype: object

In [45]:
 # Use pd.to_numeric() method to convert the datatype of the Amount column
df['Perpetrator Age'] = pd.to_numeric(df['Perpetrator Age'])

In [46]:
# Display an overview of the Weapon column
df['Weapon'].value_counts()

Handgun          226902
Knife             56494
Blunt Object      44674
Firearm           39066
Unknown           26415
Shotgun           16779
Rifle             13911
Strangulation      4598
Fire               3694
Suffocation        2752
Gun                1872
Drugs              1324
Drowning            664
Explosives          378
Poison              291
Fall                109
Name: Weapon, dtype: int64

In [47]:
# Display an overview of the Agency Type column
df['Agency Type'].value_counts()

Municipal Police    340563
Sheriff              71038
County Police        17082
State Police          8986
Special Police        2058
Regional Police        157
Tribal Police           39
Name: Agency Type, dtype: int64

In [48]:
# Display a statistical overview
df['Victim Age'].describe().round()

count    439923.0
mean         35.0
std          45.0
min           0.0
25%          21.0
50%          29.0
75%          41.0
max         998.0
Name: Victim Age, dtype: float64

In [49]:
df.to_csv('../Resources/cleaned_database.csv', index=False)